name: "Backlog Notify"
description: "Notify commit messages to Backlog issue"
author: "Takanori Oishi"
branding:
  icon: "bell"
  color: "green"
runs:
  using: "node12"
  main: "dist/index.js"
inputs:
  project_key:
    description: Backlog Project key
    required: true
  api_host:
    description: Backlog Host name
    required: true
  api_key:
    description: Backlog Api key
    required: true
  fix_keywords:
    description: Keywords to change the status of the issue to fixed
    required: false
    default: |-
      '#fix'
      '#fixes'
      '#fixed'
  close_keywords:
    description: Keywords to change the status of the issue to closed
    required: false
    default: |-
      '#close'
      '#closes'
      '#closed'
  push_comment_template:
    description: The template for backlog issue comment on push events
    required: false
    default: |-
      <%= commits[0].author.name %>さんがプッシュしました
      <% commits.forEach(commit=>{ %>\n+ <%= commit.message %> ([<%= commit.id_short %>](<%= commit.url %>))<% }); %>
  commit_message_reg_template:
    description: The template for regular expressions to parse commit  messages
    required: false
    default: ^(<%= project_key %>\\-\\d+)\\s?(.*?)?\\s?(<% fixKeywords.join("|") %>|<% closeKeywords.join("|") %>)?$
  fix_status_id:
    description: Status ID to mark as fixed
    required: false
    default: 3
  close_status_id:
    description: Status ID to mark as closed
    required: false
    default: 4
