name: actionlint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  actionlint:
    name: Lint GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-actionlint@v1
